Repository simple-login/app, pull requests merged in 2022-06, with the labels that each got.

#1028 Store hmaced partner api tokens
  app/config.py
  app/models.py
  example.env
  migrations/versions/2022_052516_2b1d3cd93e4b_update_partner_api_token_token_length.py
  tests/models/test_partner_api_token.py
Labels: enhancement

#1035 Notify user cycle email
  email_handler.py
  templates/dashboard/notification.html
  templates/notification/cycle-email.html
Labels: feature

#1059 only allow to copy the api key when it is created
  app/dashboard/views/api_key.py
  templates/dashboard/api_key.html
  templates/dashboard/new_api_key.html
Labels: enhancement

#1065 Add missing rate limits
  app/auth/views/forgot_password.py
  app/dashboard/views/pricing.py
Labels: fix

#1040 Separate code for proton callback handler
  app/account_linking.py
  app/auth/views/proton.py
  app/dashboard/views/setting.py
  app/errors.py
  app/models.py
  app/proton/proton_callback_handler.py
  app/proton/proton_client.py
  migrations/versions/2022_060908_82d3c7109ffb_partner_user_and_partner_subscription.py
  tests/models/test_partner_subscription.py
  tests/proton/test_proton_callback_handler.py
  tests/test_account_linking.py
  tests/utils.py
Labels: enhancement

#1067 Do not report complaints for deleted aliases
  app/handler/provider_complaint.py
  app/models.py
Labels: fix

#1066 use responseBody.Latest_receipt_info and not responseBody.Receipt.In_app
  app/api/views/apple.py
Labels: fix

#1080 Store transfer tokens hashed in the db and only allow them to be valid for 24 hours
  app/config.py
  app/dashboard/views/alias_transfer.py
  app/models.py
  migrations/versions/2022_061310_a7bcb872c12a_add_alias_transfer_token_expiration.py
  templates/dashboard/alias_transfer_send.html
Labels: feature

#1085 Fix: logic failed the onboarding-1 job
  job_runner.py
Labels: fix

#1075 handle subscription_payment_refunded event
  server.py
Labels: enhancement

#1087 Allow extra headers on proton connection
  app/auth/views/proton.py
  app/config.py
  app/proton/proton_client.py
Labels: enhancement

#1089 Emit events on proton actions
  app/account_linking.py
  app/dashboard/views/setting.py
Labels: enhancement

#1091 Add Proton logo to buttons
  static/images/proton.svg
  templates/auth/login.html
  templates/dashboard/setting.html
Labels: enhancement

#1092 Hide proton integration behind cookie
  app/auth/views/login.py
  app/config.py
  app/dashboard/views/setting.py
  app/internal/__init__.py
  app/internal/base.py
  app/internal/integrations.py
  app/proton/utils.py
  example.env
  server.py
Labels: enhancement

#1096 Fix double backslash open redirect
  app/utils.py
  tests/test_utils.py
Labels: bug

#1093 Add extension_redirect endpoint
  app/onboarding/__init__.py
  app/onboarding/utils.py
  app/onboarding/views/account_activated.py
  app/onboarding/views/extension_redirect.py
  tests/test_onboarding.py
Labels: enhancement

#1095 Allow to create users from partner
  app/account_linking.py
  app/models.py
  app/proton/proton_callback_handler.py
  tests/models/test_user.py
  tests/proton/test_proton_callback_handler.py
  tests/test_account_linking.py
Labels: enhancement

#1099 Send welcome mail to proton created users
  app/config.py
  app/models.py
  job_runner.py
  static/logo-sl-proton.svg
  templates/emails/base.html
  templates/emails/com/onboarding/welcome-proton-user.html
  templates/emails/com/onboarding/welcome-proton-user.txt.jinja2
  tests/jobs/test_send_proton_welcome.py
  tests/models/test_user.py
Labels: feature

#1101 Send email to users with a subscription and a partner plan upgrade
  app/account_linking.py
  app/admin_model.py
  app/auth/views/proton.py
  app/config.py
  app/dashboard/views/billing.py
  app/dashboard/views/coupon.py
  app/dashboard/views/delete_account.py
  app/dashboard/views/lifetime_licence.py
  app/dashboard/views/pricing.py
  app/dashboard/views/setting.py
  app/models.py
  app/proton/proton_callback_handler.py
  app/proton/utils.py
  cron.py
  init_app.py
  templates/emails/transactional/double-subscription-partner.html
  templates/emails/transactional/double-subscription-partner.txt.jinja2
  tests/email_tests/test_rate_limit.py
  tests/proton/test_proton_callback_handler.py
  tests/test_account_linking.py
  tests/test_models.py
Labels: feature

#1105 Fix: Missing renamed methods
  templates/dashboard/pricing.html
  templates/dashboard/setting.html
Labels: bug

#1107 allow to hide some public domains and set their order
  app/models.py
  migrations/versions/2022_062217_673a074e4215_.py
  tests/dashboard/test_custom_alias.py
Labels: enhancement

#1106 Propose upgrade proton account for proton partner users without paid mail plan
  app/dashboard/views/pricing.py
  static/style.css
  templates/dashboard/pricing.html
Labels: enhancement

#1108 Allow to set sudo mode for api requests
  app/api/__init__.py
  app/api/base.py
  app/api/views/sudo.py
  app/models.py
  docs/api.md
  migrations/versions/2022_062218_d1fb679f7eec_add_sudo_expiration_for_apikeys.py
  tests/api/test_sudo.py
Labels: feature

#1112 Show premium subscription managed by partner
  app/dashboard/views/setting.py
  templates/dashboard/setting.html
Labels: enhancement

#1111 Always check redirect_uri for oauth
  app/oauth/views/authorize.py
  templates/oauth/authorize.html
  tests/oauth/test_authorize.py
Labels: enhancement

#1113 Add state management to job
  app/models.py
  job_runner.py
  migrations/versions/2022_062714_bfebc2d5c719_add_state_to_job.py
Labels: enhancement

#1120 small refactoring
  app/dashboard/views/pricing.py
  templates/dashboard/setting.html
Labels: enhancement

#1119 update welcome proton user email
  templates/emails/com/onboarding/welcome-proton-user.html
  templates/emails/com/onboarding/welcome-proton-user.txt.jinja2
Labels: enhancement

#1123 Validate user uploaded image
  app/dashboard/views/setting.py
  app/image_validation.py
  tests/data/1px.jpg
  tests/data/1px.webp
  tests/test_image_validation.py
Labels: enhancement

#1090 Refactor unsubscribe handling
  app/handler/unsubscribe_encoder.py
  app/handler/unsubscribe_generator.py
  app/handler/unsubscribe_handler.py
  app/models.py
  email_handler.py
  templates/emails/transactional/unsubscribe-block-contact.txt.jinja2
  tests/dashboard/test_directory.py
  tests/handler/test_unsubscribe_encoder.py
  tests/handler/test_unsubscribe_generator.py
  tests/handler/test_unsubscribe_handler.py
Labels: enhancement
