Repository simple-login/app, pull requests merged in 2022-08, with the labels that each got.

#1213 fix paddle refund
  server.py
Labels: fix

#1223 add more logging
  app/alias_utils.py
Labels: enhancement

#1221 Rate limiting depending on user authenticated status
  app/extensions.py
  tests/test_extensions.py
Labels: enhancement

#1224 Generate a web session from an api key
  app/api/views/user.py
  app/auth/__init__.py
  app/auth/views/api_to_cookie.py
  app/models.py
  cron.py
  docs/api.md
  migrations/versions/2022_081016_9cc0f0712b29_add_api_to_cookie_token.py
  tests/api/test_user.py
  tests/auth/test_api_to_cookie.py
  tests/test_cron.py
Labels: feature

#1226 Support next with Proton Link
  app/account_linking.py
  app/auth/views/proton.py
  app/proton/proton_callback_handler.py
  app/utils.py
Labels: enhancement

#1230 Fixes for connect with proton on mobile
  app/api/views/setting.py
  app/api/views/user_info.py
  app/auth/views/api_to_cookie.py
  app/auth/views/proton.py
  app/dashboard/views/setting.py
  app/proton/utils.py
  tests/api/test_user_info.py
Labels: fix

#1231 Do not crash if action is unknown
  app/auth/views/proton.py
Labels: fix
