Repository simple-login/app, pull requests merged in 2022-10, with the labels that each got.

#1317 Display recovery codes for mfa only once
  app/auth/views/recovery.py
  app/config.py
  app/dashboard/__init__.py
  app/dashboard/views/fido_setup.py
  app/dashboard/views/mfa_setup.py
  app/dashboard/views/recovery_code.py
  app/models.py
  migrations/versions/2022_092716_bd95b2b4217f_updated_recovery_code_string_length.py
  shell.py
  templates/dashboard/recovery_code.html
  templates/dashboard/setting.html
  tests/test.env
Labels: enhancement

#1335 Replace reverse alias
  app/config.py
  email_handler.py
  tests/example_emls/replacement_on_reply_phase.eml
  tests/test.env
  tests/test_email_handler.py
Labels: fix

#1337 do not quarantine an email if fails DMARC but has a small rspamd score
  app/config.py
  app/handler/dmarc.py
  app/handler/spamd_result.py
  tests/example_emls/dmarc_cannot_parse_rspamd_score.eml
  tests/handler/test_spamd_result.py
Labels: enhancement

#1334 Have custom domains set up multiple dkim records to be able to rotate keys
  app/custom_domain_validation.py
  app/dashboard/views/domain_detail.py
  templates/dashboard/domain_detail/dns.html
Labels: enhancement

#1358 Fix: Add csrf verification to directory updates
  app/dashboard/views/alias_contact_manager.py
  app/dashboard/views/alias_transfer.py
  app/dashboard/views/batch_import.py
  app/dashboard/views/delete_account.py
  app/dashboard/views/directory.py
  app/dashboard/views/domain_detail.py
  app/dashboard/views/index.py
  app/dashboard/views/mailbox.py
  app/dashboard/views/mailbox_detail.py
  app/dashboard/views/setting.py
  app/utils.py
  templates/dashboard/alias_contact_manager.html
  templates/dashboard/alias_transfer_send.html
  templates/dashboard/batch_import.html
  templates/dashboard/delete_account.html
  templates/dashboard/directory.html
  templates/dashboard/domain_detail/dns.html
  templates/dashboard/domain_detail/info.html
  templates/dashboard/domain_detail/trash.html
  templates/dashboard/index.html
  templates/dashboard/mailbox.html
  templates/dashboard/mailbox_detail.html
  templates/dashboard/setting.html
  tests/dashboard/test_directory.py
Labels: fix

#1360 Feat: Added parallel limiter to prevent sqlalchemy transaction issues
  .github/workflows/main.yml
  app/api/views/new_custom_alias.py
  app/api/views/new_random_alias.py
  app/dashboard/views/alias_contact_manager.py
  app/dashboard/views/coupon.py
  app/dashboard/views/custom_alias.py
  app/dashboard/views/index.py
  app/parallel_limiter.py
  app/redis_services.py
  app/session.py
  server.py
  tests/test.env
  tests/test_prarallel_limiter.py
Labels: feature

#1379 Fix: Use source ip if user is not authenticated
  app/parallel_limiter.py
Labels: fix

#1378 Added test for too many requests for the parallel limiter
  tests/test_prarallel_limiter.py
Labels: enhancement
