Repository simple-login/app, pull requests merged in 2022-07, with the labels that each got.

#1130 Feature: Use new job status to retry killed jobs
  app/config.py
  job_runner.py
  tests/jobs/test_job_runner.py
Labels: feature

#1132 Feature: Add delete account route for the api
  app/api/__init__.py
  app/api/views/user.py
  docs/api.md
  tests/api/test_user.py
Labels: feature

#1135 Compute Proton metrics
  app/models.py
  cron.py
  migrations/versions/2022_070218_516c21ea7d87_.py
  migrations/versions/2022_070218_bd7d032087b2_.py
Labels: feature

#1137 Fix: When logging with parter create accounts with lowercase emails
  app/account_linking.py
  tests/test_account_linking.py
Labels: fix

#1136 add 14 days mention and use same stats design for alias activity page
  templates/dashboard/alias_log.html
  templates/dashboard/index.html
Labels: enhancement

#1139 show msg on /internal/integrations/proton
  app/internal/integrations.py
  templates/dashboard/setting.html
Labels: enhancement

#1140 Capture exception on Login with Proton
  app/auth/views/proton.py
Labels: fix

#1141 Allow to login with proton to enter sudo mode
  app/auth/views/fido.py
  app/auth/views/login_utils.py
  app/dashboard/views/enter_sudo.py
  app/internal/__init__.py
  app/internal/exit_sudo.py
  templates/dashboard/enter_sudo.html
Labels: feature

#1142 Bypass 2FA if Login with Proton
  app/auth/views/login_utils.py
  app/auth/views/proton.py
  templates/dashboard/enter_sudo.html
Labels: feature

#1146 Fix: Add more weird encodings to the known encoding list
  app/email_utils.py
Labels: fix

#1144 add nb_proton_user, nb_proton_premium to daily metric email
  cron.py
Labels: enhancement

#1145 Fix: Check if required session headers exist
  app/auth/views/proton.py
Labels: fix

#1151 Fix: Allow internal link independent of enable log in with proton
  app/config.py
  app/internal/integrations.py
Labels: fix

#1160 Sanitize the highlight contact id
  app/dashboard/views/alias_contact_manager.py
  server.py
Labels: fix

#1161 Limit amount of imports
  app/dashboard/views/batch_import.py
  server.py
Labels: fix

#1166 Allow to configure mem storage from config
  app/config.py
  poetry.lock
  pyproject.toml
  server.py
Labels: feature

#1148 Allow users to keep the original unsub behaviour
  app/config.py
  app/dashboard/views/setting.py
  app/dashboard/views/unsubscribe.py
  app/handler/unsubscribe_encoder.py
  app/handler/unsubscribe_generator.py
  app/handler/unsubscribe_handler.py
  app/models.py
  migrations/versions/2022_070619_b0101a66bb77_add_unsubscribe_behaviour.py
  templates/dashboard/setting.html
  tests/handler/test_unsubscribe_encoder.py
  tests/handler/test_unsubscribe_generator.py
  tests/handler/test_unsubscribe_handler.py
Labels: feature

#1155 Restrict the number of free alias for new free users
  app/api/views/user_info.py
  app/config.py
  app/models.py
  docs/api.md
  tests/api/test_user_info.py
Labels: feature

#1174 Change default unsub behaviour to disable alias by default
  app/models.py
  migrations/versions/2022_072011_89081a00fc7d_default_unsub_behaviour.py
Labels: enhancement

#1186 Implement mode for Login with Proton
  app/auth/views/proton.py
Labels: enhancement

#1189 remove envs used for proton beta link
  app/auth/views/login.py
  app/config.py
  app/dashboard/views/enter_sudo.py
  app/dashboard/views/setting.py
  app/internal/integrations.py
  app/proton/utils.py
Labels: enhancement

#1191 Remove ResetCodes after email change
  app/auth/views/change_email.py
  tests/auth/test_change_email.py
Labels: bug, enhancement

#1192 Added rate limit to resend activation email
  app/auth/views/resend_activation.py
Labels: fix

#1195 Update Dockerfile to use python 3.10
  Dockerfile
Labels: enhancement

#1198 Do not allow SVG image uploads
  app/image_validation.py
  tests/test_image_validation.py
Labels: enhancement
