Repository simple-login/app, pull requests merged in 2022-11, with the labels that each got.

#1393 Feature: Add app name to each db connection
  app/config.py
  app/db.py
Labels: enhancement

#1394 Feat: Re-deliver mails
  app/mail_sender.py
  cron.py
  crontab.yml
  tests/test_mail_sender.py
Labels: feature

#1397 Fix: Do not re-re-deliver unsent mails on failure to re-deliver
  app/mail_sender.py
  tests/test_mail_sender.py
Labels: fix

#1401 Fix: Only override postfix port when enabling TLS if the port is set to be 25
  app/config.py
  app/mail_sender.py
Labels: fix

#1411 Fix: When re-sending emails if they trigger exceptions move out of failed dir
  app/mail_sender.py
  tests/test_mail_sender.py
Labels: enhancement

#1432 Fix: replace mailbox email for alias email in the message content for the reply phase
  email_handler.py
Labels: fix

#1383 Simpler csv export
  CONTRIBUTING.md
  app/alias_utils.py
  app/api/views/export.py
  app/dashboard/__init__.py
  app/dashboard/views/alias_export.py
  scripts/reset_local_db.sh
  scripts/reset_test_db.sh
  templates/dashboard/setting.html
  tests/api/test_import_export.py
  tests/dashboard/test_alias_csv_export.py
  tests/utils_test_alias.py
Labels: enhancement

#1458 Use canonical email when registering users
  app/admin_model.py
  app/api/views/auth.py
  app/auth/views/forgot_password.py
  app/auth/views/login.py
  app/auth/views/register.py
  app/auth/views/resend_activation.py
  app/config.py
  app/dashboard/views/setting.py
  app/email_utils.py
  app/import_utils.py
  app/utils.py
  pyproject.toml
  tests/api/test_auth.py
  tests/auth/test_login.py
  tests/auth/test_register.py
  tests/dashboard/test_setting.py
  tests/test.env
  tests/test_utils.py
  tests/utils.py
Labels: fix

#1459 Keep dirty email after registration
  app/api/views/auth.py
  app/auth/views/change_email.py
  app/auth/views/register.py
  app/dashboard/views/setting.py
  app/fake_data.py
  app/models.py
  migrations/versions/2022_113018_74fe25b66e9b_.py
Labels: enhancement
