Repository simple-login/app, pull requests merged in 2022-05, with the labels that each got.

#953 handle case user doesn't have default domain for alias
  templates/dashboard/setting.html
Labels: bug

#972 Generate release notes when creating a tag
  .github/changelog_configuration.json
  .github/workflows/main.yml
Labels: enhancement

#974 Fix: Track processes that start with the same chars independently (smtp vs stmpd)
  monitoring.py
  tests/test_monitoring.py
Labels: bug

#976 Fix Slack notification
  .github/changelog_configuration.json
  .github/workflows/main.yml
Labels: enhancement

#977 Obtain git information from version file
  .dockerignore
  .github/workflows/main.yml
  .version
  app/build_info.py
  app/config.py
  app/monitor/views.py
  server.py
Labels: bug

#981 Action refactor: Only run on push and also send to slack the commit sha
  .github/workflows/main.yml
Labels: enhancement

#988 Fix: Sanitize directory name before displaying it to the user
  templates/dashboard/directory.html
Labels: bug

#921 Prevent free users from creating reverse-alias
  app/api/views/alias.py
  app/config.py
  app/dashboard/views/alias_contact_manager.py
  app/errors.py
  app/models.py
  docs/api.md
  migrations/versions/2022_051213_088f23324464_add_flags_to_the_user_model.py
  scripts/new-migration.sh
  templates/dashboard/alias_contact_manager.html
  tests/api/test_alias.py
Labels: feature

#986 Add extension onboarding pages
  app/email_utils.py
  app/onboarding/__init__.py
  app/onboarding/base.py
  app/onboarding/views/final.py
  app/onboarding/views/index.py
  server.py
  static/images/onboarding-click-icon.png
  static/images/onboarding-right-click.png
  templates/emails/transactional/test-email.html
  templates/emails/transactional/test-email.txt
  templates/onboarding/final.html
  templates/onboarding/index.html
Labels: feature

#963 Handle complaints that have multiple recipients
  CONTRIBUTING.md
  app/email/headers.py
  app/email_utils.py
  app/handler/provider_complaint.py
  scripts/reset_local_db.sh
  scripts/reset_test_db.sh
  templates/emails/transactional/provider-complaint-forward-phase.html
  templates/emails/transactional/provider-complaint-forward-phase.txt.jinja2
  tests/example_emls/hotmail_complaint.eml
  tests/example_emls/yahoo_complaint.eml
  tests/handler/test_provider_complaints.py
  tests/test.env
Labels: bug

#993 update the email wording
  templates/emails/transactional/non-reverse-alias-reply-phase.txt.jinja2
Labels: enhancement

#995 allow to use a different from for send_email()
  app/email_utils.py
Labels: enhancement

#1000 remove the drag and drop mention for now
  templates/dashboard/contact_detail.html
  templates/dashboard/mailbox_detail.html
Labels: enhancement

#997 Adapt extension setup
  app/onboarding/__init__.py
  app/onboarding/views/index.py
  app/onboarding/views/setup_done.py
  templates/onboarding/final.html
  templates/onboarding/index.html
  templates/onboarding/setup_done.html
Labels: feature

#1011 Fix tests to allow re-running them locally without colliding with previous runs
  local_data/test_words.txt
  pytest.ci.ini
  scripts/run-test.sh
  tests/api/test_import_export.py
  tests/dashboard/test_custom_alias.py
  tests/test_alias_utils.py
  tests/test_email_handler.py
Labels: enhancement

#1012 tweak the account activated page ui
  templates/onboarding/account_activated.html
Labels: enhancement

#1013 Menu optimize
  templates/header.html
  templates/menu.html
Labels: enhancement

#1019 Receive partner as param in ProtonCallbackHandler
  app/auth/views/proton.py
  app/dashboard/views/setting.py
  app/proton/proton_callback_handler.py
  tests/proton/test_proton_callback_handler.py
Labels: enhancement

#1014 add mention about the limit of 15 aliases into the header
  templates/header.html
Labels: enhancement

#1022 Save unsent emails to disk to be resent later
  app/config.py
  app/mail_sender.py
  tests/handler/test_provider_complaints.py
  tests/test_mail_sender.py
Labels: feature
