Repository simple-login/app, pull requests merged in 2023-01, with the labels that each got.

#1519 Manual sub reminder
  templates/dashboard/pricing.html
  templates/emails/transactional/manual-subscription-end.html
  templates/emails/transactional/manual-subscription-end.txt
Labels: enhancement

#1522 Fix: typo in the message
  app/handler/unsubscribe_handler.py
Labels: fix

#1525 Added parallel limiting to several routes
  app/dashboard/views/custom_domain.py
  app/dashboard/views/directory.py
  app/dashboard/views/mailbox.py
  app/dashboard/views/subdomain.py
Labels: fix

#1524 Fix: Use timed signers to avoid leaving permanent links in mailbox change and verification
  app/dashboard/views/mailbox.py
  app/dashboard/views/mailbox_detail.py
  templates/emails/transactional/verify-mailbox-change.html
  templates/emails/transactional/verify-mailbox-change.txt.jinja2
  templates/emails/transactional/verify-mailbox.html
  templates/emails/transactional/verify-mailbox.txt.jinja2
Labels: fix

#1523 Fix: Add CSRF validation to api key management page
  app/dashboard/views/api_key.py
  app/dashboard/views/batch_import.py
  app/dashboard/views/mfa_cancel.py
  app/dashboard/views/subdomain.py
  templates/dashboard/api_key.html
  templates/dashboard/mfa_cancel.html
  templates/dashboard/subdomain.html
Labels: fix

#1543 Fix: Use npm ci instead of install to prevent install different versions
  Dockerfile
Labels: fix

#1534 Tranfer aliases to a new mailbox when deleting mailboxes
  .gitignore
  app/api/views/mailbox.py
  app/dashboard/views/mailbox.py
  docs/api.md
  job_runner.py
  templates/dashboard/mailbox.html
  tests/jobs/test_delete_mailbox_job.py
Labels: feature

#1503 Set the proper link for unsub newsletter
  app/handler/unsubscribe_encoder.py
  app/newsletter_utils.py
Labels: fix

#1545 Fix: Allow receive email from non-canonical sources
  email_handler.py
  tests/test_email_handler.py
Labels: fix
