Repository simple-login/app, pull requests merged in 2025-03, with the labels that each got.

#2406 deps: update flask-limiter and redis deps
  pyproject.toml
  tests/api/test_new_custom_alias.py
  tests/api/test_new_random_alias.py
  tests/dashboard/test_custom_alias.py
  tests/dashboard/test_index.py
  tests/test_extensions.py
  tests/utils.py
  uv.lock
Labels: dependencies

#2418 feat: alias restore check quota
  app/alias_delete.py
  app/dashboard/views/alias_trash.py
  app/errors.py
  app/models.py
  tests/test_alias_delete.py
Labels: enhancement

#2419 Preserve Unsubscribe header and create one that always unsubs via alias
  app/email/headers.py
  app/handler/unsubscribe_generator.py
  tests/handler/test_unsubscribe_generator.py
Labels: feature

#2423 fix: only allow api_to_cookie if is for same user
  app/auth/views/api_to_cookie.py
  tests/auth/test_api_to_cookie.py
Labels: fix

#2427 fix: alias trash copy
  templates/dashboard/index.html
Labels: enhancement

#2428 fix: limit schemes for proton oauth
  app/auth/views/proton.py
  app/config.py
Labels: fix

#2429 fix: trash custom domain alias deletes it
  app/alias_delete.py
  tests/tasks/test_delete_custom_domain_job.py
  tests/test_alias_delete.py
Labels: fix
